name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
    
      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML
        run: |
          mkdir -p public
          pandoc documentation/index.md -s --template documentation/html/index.html -o public/index.html --metadata=link-citations=true    
          pandoc documentation/dsn2Sheet.md -s --template documentation/html/index.html -o public/dsn2Sheet.html  --metadata=link-citations=true   
          pandoc documentation/dsn2Text.md -s --template documentation/html/index.html -o public/dsn2Text.html  --metadata=link-citations=true   


      - name: Copy CSS
        run: cp documentation/html/index.css public/index.css

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
