name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust environment
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo2junit
        run: cargo install cargo2junit

      - name: Run integration tests and generate JUnit report
        run: |
          # Run all integration tests (those in the `tests` directory)
          cargo test -- --nocapture > test_output.log || true

          # Convert test results to JUnit XML
          cargo2junit < test_output.log > tests.xml || true

          # Verify the existence of tests.xml
          ls -l tests.xml || true
          cat tests.xml || true

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: tests.xml

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: test-results
          path: public/tests.xml

      - name: Include Test Results in Documentation
        run: |
          ls -l tests.xml || true
          cat tests.xml || true
          cp tests.xml public/
          #pandoc tests.xml -s --no-highlight --template documentation/html/index.html -o public/test_results.html

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Install sed
        run: sudo apt-get install -y sed

      - name: Convert Markdown to HTML
        run: |
          mkdir -p public
          pandoc documentation/index.md -s --no-highlight --template documentation/html/index.html -o public/index.html
          pandoc documentation/dsn2Sheet.md -p -s --no-highlight --template documentation/html/index.html -o public/dsn2Sheet.html   
          sed -i 's/^\s*<span/<span/g' "public/dsn2Sheet.html"     
          sed -i 's/^\s*\([^<]\)/\1/g' "public/dsn2Sheet.html"   
          pandoc documentation/dsn2Text.md -s --no-highlight --template documentation/html/index.html -o public/dsn2Text.html     
          sed -i 's/^\s*<span/<span/g' "public/dsn2Text.html"     
          sed -i 's/^\s*\([^<]\)/\1/g' "public/dsn2Text.html"

      - name: Copy CSS
        run: cp documentation/html/index.css public/index.css

      - name: Include Test Results in Documentation
        run: |
          ls -l tests.xml || true
          cat tests.xml || true
          cp tests.xml public/
          #pandoc tests.xml -s --no-highlight --template documentation/html/index.html -o public/test_results.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
